image: docker:20.10.21
stages:
  - build
  - deploy

before_script:
    - docker --version

buildContainer:
  stage: build
  image: docker:20.10.21
  script:
    - docker build -f build.Dockerfile . -t kcb-ses-poc-be:v1.0.0

runUpdatedBuild:
  stage: deploy
  image: cytopia/ansible:2.8-awsk8s-manifest-linux-arm64
  script:
    - ansible --version
    - ansible-playbook --version