image: docker:20.10.21
stages:
  - build
  - deploy

buildContainer:
  stage: build
  image: docker:20.10.21
  script:
    - docker build -f build.Dockerfile . -t kcb-ses-poc-be:v1.0.0

runUpdatedBuild:
  stage: deploy
  image: codeyourinfra/myansible:latest
  script:
    - ansible --version
    - ansible-playbook --version