image: docker:20.10.21
stages:
  - build
  - deploy

buildContainer:
  stage: build
  image: docker:20.10.21
  script:
    - docker build -f build.Dockerfile . -t kcb-ses-poc-be:v1.0.0

runUpdatedBuild:
  stage: deploy
  #image: codeyourinfra/myansible:latest
  image: lusengeri/my-ansible:latest
  script:
    - ansible --version
    - ansible-playbook --version
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - eval "$(ssh-agent -s)"
   # - ansible-playbook test_env_playbook.yml -i 10.20.2.12, -u manzagi --private-key /root/.ssh/id_rsa