spring:
  datasource:
#    url: jdbc:mysql://172.16.189.128:3306/kcb_fs_db?serverTimezone=UTC
#    username: jpa_account
#    password: Cvs@1234
    url: jdbc:mysql://10.20.2.51:3306/kcb_sales_effective?serverTimezone=EAT
    username: wgicheru
    password: 1QAZ2wsx3edc.
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      globally_quoted_identifiers: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      database: MYSQL
      ddl-auto: create-drop
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
#            storage_engine: innodb
          format_sql: true