spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/kcb_db
    password: Makuba33159718
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: rpc-wallet-db
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true